import type { Container, AppService, SystemService } from "./types";

export const CONTAINERS: Container[] = [
  {
    id: "c1",
    name: "nginx",
    image: "nginx:1.25-alpine",
    status: "running",
    health: "healthy",
    cpu: "0.4%",
    cpuNum: 0.4,
    memory: "18 MB",
    memNum: 18,
    memLimit: "256 MB",
    net: "↓1.2 ↑340",
    ports: "80, 443",
    created: "Jan 1",
    uptime: "14d 8h",
    restarts: 1,
    networkMode: "bridge",
    ip: "172.17.0.2",
    mac: "02:42:ac:11:00:02",
  },
  {
    id: "c2",
    name: "postgres",
    image: "postgres:16",
    status: "running",
    health: "healthy",
    cpu: "2.1%",
    cpuNum: 2.1,
    memory: "142 MB",
    memNum: 142,
    memLimit: "512 MB",
    net: "↓240 ↑80",
    ports: "5432",
    created: "Jan 1",
    uptime: "14d 8h",
    restarts: 0,
    networkMode: "bridge",
    ip: "172.17.0.3",
    mac: "02:42:ac:11:00:03",
  },
  {
    id: "c3",
    name: "redis",
    image: "redis:7.2-alpine",
    status: "running",
    health: "healthy",
    cpu: "0.1%",
    cpuNum: 0.1,
    memory: "12 MB",
    memNum: 12,
    memLimit: "128 MB",
    net: "↓80 ↑40",
    ports: "6379",
    created: "Jan 1",
    uptime: "14d 8h",
    restarts: 0,
    networkMode: "bridge",
    ip: "172.17.0.4",
    mac: "02:42:ac:11:00:04",
  },
  {
    id: "c4",
    name: "nextcloud",
    image: "nextcloud:28-apache",
    status: "running",
    health: "healthy",
    cpu: "0.8%",
    cpuNum: 0.8,
    memory: "311 MB",
    memNum: 311,
    memLimit: "1 GB",
    net: "↓890 ↑210",
    ports: "8080",
    created: "Jan 8",
    uptime: "7d 2h",
    restarts: 2,
    networkMode: "bridge",
    ip: "172.17.0.5",
    mac: "02:42:ac:11:00:05",
  },
  {
    id: "c5",
    name: "grafana",
    image: "grafana/grafana:10.2",
    status: "running",
    health: "healthy",
    cpu: "1.2%",
    cpuNum: 1.2,
    memory: "98 MB",
    memNum: 98,
    memLimit: "256 MB",
    net: "↓120 ↑45",
    ports: "3000",
    created: "Jan 8",
    uptime: "7d 2h",
    restarts: 0,
    networkMode: "bridge",
    ip: "172.17.0.6",
    mac: "02:42:ac:11:00:06",
  },
  {
    id: "c6",
    name: "prometheus",
    image: "prom/prometheus:v2.48",
    status: "stopped",
    health: "none",
    cpu: "—",
    cpuNum: 0,
    memory: "—",
    memNum: 0,
    memLimit: "512 MB",
    net: "—",
    ports: "9090",
    created: "Jan 12",
    uptime: "—",
    restarts: 0,
    networkMode: "bridge",
    ip: "—",
    mac: "—",
  },
  {
    id: "c7",
    name: "loki",
    image: "grafana/loki:2.9",
    status: "stopped",
    health: "none",
    cpu: "—",
    cpuNum: 0,
    memory: "—",
    memNum: 0,
    memLimit: "512 MB",
    net: "—",
    ports: "3100",
    created: "Jan 12",
    uptime: "—",
    restarts: 0,
    networkMode: "bridge",
    ip: "—",
    mac: "—",
  },
  {
    id: "c8",
    name: "traefik",
    image: "traefik:v3.0",
    status: "restarting",
    health: "unhealthy",
    cpu: "1.8%",
    cpuNum: 1.8,
    memory: "42 MB",
    memNum: 42,
    memLimit: "128 MB",
    net: "↓340 ↑120",
    ports: "80, 8080",
    created: "Jan 10",
    uptime: "22m",
    restarts: 4,
    networkMode: "bridge",
    ip: "172.17.0.7",
    mac: "02:42:ac:11:00:07",
  },
];

export const APPLICATIONS: AppService[] = [
  {
    id: "app1",
    name: "Nextcloud",
    description: "Self-hosted cloud storage and collaboration suite",
    status: "running",
    containers: 3,
    version: "28.0.3",
    category: "Storage",
    icon: "☁",
  },
  {
    id: "app2",
    name: "Gitea",
    description: "Lightweight self-hosted Git service",
    status: "running",
    containers: 2,
    version: "1.21.4",
    category: "Development",
    icon: "🐙",
  },
  {
    id: "app3",
    name: "Jellyfin",
    description: "Free software media server and streaming platform",
    status: "stopped",
    containers: 1,
    version: "10.8.13",
    category: "Media",
    icon: "📺",
  },
  {
    id: "app4",
    name: "Grafana",
    description: "Observability and data visualization platform",
    status: "running",
    containers: 2,
    version: "10.2.0",
    category: "Monitoring",
    icon: "📊",
  },
  {
    id: "app5",
    name: "Vaultwarden",
    description: "Lightweight Bitwarden-compatible password manager",
    status: "running",
    containers: 1,
    version: "1.30.1",
    category: "Security",
    icon: "🔐",
  },
  {
    id: "app6",
    name: "Immich",
    description: "High-performance self-hosted photo and video backup",
    status: "stopped",
    containers: 4,
    version: "1.92.1",
    category: "Media",
    icon: "📷",
  },
  {
    id: "app7",
    name: "Home Assistant",
    description: "Open-source home automation platform",
    status: "stopped",
    containers: 1,
    version: "2024.1",
    category: "Automation",
    icon: "🏠",
  },
  {
    id: "app8",
    name: "Prometheus",
    description: "Metrics-based monitoring and alerting toolkit",
    status: "stopped",
    containers: 1,
    version: "2.48.1",
    category: "Monitoring",
    icon: "📈",
  },
];

export const SERVICES: SystemService[] = [
  {
    id: "s1",
    name: "docker.service",
    description: "Docker Application Container Engine",
    status: "active",
    enabled: true,
    cpu: "0.3%",
    memory: "128 MB",
    uptime: "14d 8h",
  },
  {
    id: "s2",
    name: "nginx.service",
    description: "A high performance web server",
    status: "active",
    enabled: true,
    cpu: "0.1%",
    memory: "4 MB",
    uptime: "14d 8h",
  },
  {
    id: "s3",
    name: "ssh.service",
    description: "OpenBSD Secure Shell server",
    status: "active",
    enabled: true,
    cpu: "0.0%",
    memory: "2 MB",
    uptime: "14d 8h",
  },
  {
    id: "s4",
    name: "cron.service",
    description: "Regular background program processing",
    status: "active",
    enabled: true,
    cpu: "0.0%",
    memory: "1 MB",
    uptime: "14d 8h",
  },
  {
    id: "s5",
    name: "systemd-resolved.service",
    description: "Network Name Resolution",
    status: "active",
    enabled: true,
    cpu: "0.0%",
    memory: "6 MB",
    uptime: "14d 8h",
  },
  {
    id: "s6",
    name: "ufw.service",
    description: "Uncomplicated firewall",
    status: "active",
    enabled: true,
    cpu: "0.0%",
    memory: "1 MB",
    uptime: "14d 8h",
  },
  {
    id: "s7",
    name: "fail2ban.service",
    description: "Fail2Ban intrusion prevention",
    status: "active",
    enabled: true,
    cpu: "0.0%",
    memory: "8 MB",
    uptime: "14d 8h",
  },
  {
    id: "s8",
    name: "postgresql.service",
    description: "PostgreSQL RDBMS",
    status: "inactive",
    enabled: false,
    cpu: "—",
    memory: "—",
    uptime: "—",
  },
  {
    id: "s9",
    name: "snapd.service",
    description: "Snap Daemon",
    status: "inactive",
    enabled: false,
    cpu: "—",
    memory: "—",
    uptime: "—",
  },
  {
    id: "s10",
    name: "unattended-upgrades.service",
    description: "Unattended Upgrades Shutdown",
    status: "failed",
    enabled: true,
    cpu: "—",
    memory: "—",
    uptime: "—",
  },
];

export const LOG_LINES = [
  {
    ts: "14:32:01.324",
    level: "INFO",
    source: "docker",
    msg: "Container nginx started successfully",
  },
  {
    ts: "14:32:08.441",
    level: "WARN",
    source: "nginx",
    msg: "Upstream timed out (110) while reading response header from upstream",
  },
  {
    ts: "14:33:10.001",
    level: "INFO",
    source: "nginx",
    msg: '192.168.1.42 "GET / HTTP/1.1" 200 615',
  },
  {
    ts: "14:35:21.882",
    level: "INFO",
    source: "system",
    msg: "Backup job completed — 2.4 GB written to /mnt/backup",
  },
  {
    ts: "14:36:44.009",
    level: "ERROR",
    source: "traefik",
    msg: "dial tcp 172.17.0.9:80 connect: connection refused",
  },
  {
    ts: "14:37:01.223",
    level: "WARN",
    source: "docker",
    msg: "Container traefik exceeded restart threshold (4)",
  },
  {
    ts: "14:38:15.882",
    level: "INFO",
    source: "sshd",
    msg: "Accepted publickey for admin from 192.168.1.42 port 54210",
  },
  {
    ts: "14:40:00.000",
    level: "INFO",
    source: "cron",
    msg: "(root) CMD (/usr/bin/certbot renew --quiet)",
  },
  {
    ts: "14:41:22.114",
    level: "INFO",
    source: "nginx",
    msg: '192.168.1.1 "POST /api/upload HTTP/1.1" 413 0',
  },
  {
    ts: "14:42:10.887",
    level: "INFO",
    source: "docker",
    msg: "Health check for container nextcloud: healthy",
  },
  {
    ts: "14:45:00.033",
    level: "INFO",
    source: "nginx",
    msg: "Signal 1 (SIGHUP) received — reloading configuration",
  },
  {
    ts: "14:48:30.221",
    level: "WARN",
    source: "postgres",
    msg: "Slow query detected: 1823ms — SELECT * FROM oc_filecache",
  },
  {
    ts: "14:51:02.119",
    level: "INFO",
    source: "system",
    msg: "Package index refreshed — 12 upgrades available",
  },
  {
    ts: "14:55:44.008",
    level: "ERROR",
    source: "fail2ban",
    msg: "Ban 203.0.113.5 — 5 failed SSH attempts in 300 seconds",
  },
  {
    ts: "15:00:00.000",
    level: "INFO",
    source: "cron",
    msg: "Scheduled tasks completed successfully",
  },
];

export const UPDATES = [
  {
    pkg: "openssh-server",
    current: "9.3p1-1ubuntu3",
    next: "9.6p1-3ubuntu13.3",
    type: "security" as const,
  },
  {
    pkg: "openssl",
    current: "3.0.2-0ubuntu1.12",
    next: "3.0.2-0ubuntu1.15",
    type: "security" as const,
  },
  {
    pkg: "curl",
    current: "7.88.1-10+deb12u4",
    next: "7.88.1-10+deb12u6",
    type: "security" as const,
  },
  {
    pkg: "linux-image-6.8",
    current: "6.8.0-40",
    next: "6.8.0-47",
    type: "security" as const,
  },
  {
    pkg: "docker-ce",
    current: "24.0.7",
    next: "25.0.2",
    type: "system" as const,
  },
  {
    pkg: "docker-ce-cli",
    current: "24.0.7",
    next: "25.0.2",
    type: "system" as const,
  },
  { pkg: "apt", current: "2.7.14", next: "2.7.15", type: "system" as const },
  {
    pkg: "python3-minimal",
    current: "3.11.2",
    next: "3.11.8",
    type: "system" as const,
  },
  {
    pkg: "libssl3",
    current: "3.0.2-0ubuntu1.12",
    next: "3.0.2-0ubuntu1.15",
    type: "security" as const,
  },
  {
    pkg: "tzdata",
    current: "2023c-0ubuntu0.22",
    next: "2024a-0ubuntu0.22",
    type: "system" as const,
  },
  {
    pkg: "git",
    current: "1:2.39.2-1.1",
    next: "1:2.43.0-1ubuntu7",
    type: "system" as const,
  },
  { pkg: "htop", current: "3.2.2-1", next: "3.3.0-4", type: "system" as const },
];

// seeded random for deterministic sparklines / charts
function seeded(s: number) {
  let x = Math.abs(s) || 0.5;
  return () => {
    x = (x * 9301 + 49297) % 233280;
    return x / 233280;
  };
}

export function buildChartData(
  base: number,
  noise: number,
  range: string,
  seed: number,
) {
  const configs: Record<string, { pts: number; label: (i: number) => string }> =
    {
      "5m": { pts: 20, label: (i) => `${i * 15}s` },
      "15m": { pts: 30, label: (i) => `${i * 30}s` },
      "30m": { pts: 30, label: (i) => `${i}m` },
      "1h": { pts: 30, label: (i) => `${i * 2}m` },
      "6h": { pts: 36, label: (i) => `${i * 10}m` },
      "7d": { pts: 42, label: (i) => `${Math.round(i * 4)}h` },
      "24h": { pts: 48, label: (i) => `${i * 30}m` },
      "30d": { pts: 60, label: (i) => `${i + 1}d` },
    };
  const cfg = configs[range] ?? configs["30m"];
  const rand = seeded(seed);
  return Array.from({ length: cfg.pts }, (_, i) => ({
    t: cfg.label(i),
    v: Math.max(
      1,
      Math.min(
        98,
        base + (rand() - 0.5) * noise * 2 + Math.sin(i / 4) * (noise * 0.25),
      ),
    ),
  }));
}
